### ISSUE TITLE
CLI stucks if not apk found

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#144]
```
Exception in thread "main" java.io.FileNotFoundException: ....../apks/androidTest.apk (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.linkedin.dex.parser.DexParser$Companion.readDexFiles(DexParser.kt:68)
	at com.linkedin.dex.parser.DexParser$Companion.findTestMethods(DexParser.kt:57)
	at com.malinskiy.marathon.android.AndroidTestParser.extract(AndroidTestParser.kt:12)
	at com.malinskiy.marathon.Marathon.runAsync(Marathon.kt:83)
	at com.malinskiy.marathon.Marathon$run$1.invokeSuspend(Marathon.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.malinskiy.marathon.Marathon.run(Marathon.kt:72)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt:37)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at com.malinskiy.marathon.cli.ApplicationViewKt.main(ApplicationView.kt:21)
```

**Comment by tagantroy** [comment]
Fixed #162
