### ISSUE TITLE
Marathon needs to understand the 'Unknown package' error

### ISSUE THREAD

**Issue by tseglevskiy** [MarathonLabs/marathon#156]
Our infrastructure cleans up new connected device, including removing app and its data. Seems like device was reconnected (possible, rebooted), testing apps was removed, but marathon recognized this device as already prepared and is trying run test on it again and again. 

I think Marathon need to understand this error and start to initialize this device from scratch again. 

```
[08:23:31] :     [Step 9/13] Exception occurred while executing:
[08:23:31] :     [Step 9/13] java.lang.IllegalArgumentException: Unknown package: com.agoda.mobile.consumer
[08:23:31] :     [Step 9/13]    at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:5080)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:27936)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:27942)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:24069)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:996)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
[08:23:31] :     [Step 9/13]    at android.os.ShellCommand.exec(ShellCommand.java:96)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:28746)
[08:23:31] :     [Step 9/13]    at android.os.Binder.shellCommand(Binder.java:581)
[08:23:31] :     [Step 9/13]    at android.os.Binder.onTransact(Binder.java:481)
[08:23:31] :     [Step 9/13]    at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3211)
[08:23:31] :     [Step 9/13]    at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5107)
[08:23:31] :     [Step 9/13]    at android.os.Binder.execTransact(Binder.java:682)
[08:23:31] :     [Step 9/13] Failure [DELETE_FAILED_INTERNAL_ERROR]
```

**Comment by tagantroy** [comment]
@tseglevskiy Please check with latest snapshot(after [this](https://github.com/Malinskiy/marathon/commit/d2f0d2b0caff38b90fd4d166d13d87d6bbc7e341) commit )

**Comment by Malinskiy** [comment]
Assuming it's fixed due to no activity. Feel free to reopen if you encounter it again
