### ISSUE TITLE
Better Error Messages on CLI

### ISSUE THREAD

**Issue by alex-apriamashvili** [MarathonLabs/marathon#258]
At the moment when a user first installs the Marathon CLI, shall (s)he try to execute `marathon` command, the execution will fail with a similar output:
```text
14:34:05.240 [main] INFO com.malinskiy.marathon.cli.ApplicationView - Starting marathon
14:34:05.437 [main] INFO com.malinskiy.marathon.cli.config.ConfigFactory - Checking Marathonfile config
14:34:05.437 [main] ERROR com.malinskiy.marathon.cli.config.ConfigFactory - No config /usr/local/Cellar/marathon/0.4.1/libexec/bin/Marathonfile present
Exception in thread "main" com.malinskiy.marathon.exceptions.ConfigurationException: No config /usr/local/Cellar/marathon/0.4.1/libexec/bin/Marathonfile present
	at com.malinskiy.marathon.cli.config.ConfigFactory.create(ConfigFactory.kt:22)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt:36)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at com.malinskiy.marathon.cli.ApplicationViewKt.main(ApplicationView.kt:25)
```
Although the reason for this failure is quite straightforward and explicitely mentioned in the output: `'No config /usr/local/Cellar/marathon/0.4.1/libexec/bin/Marathonfile present'` the rest of the output is not particularily required to be present and could be omitted.

The idea here is to remove Java exceptions from the output and prettify the error message to make it more user-friendly.
In this particular case, the preferred error message would be:
```
'Marathonfile' was not found. Please, make sure that the configuration file is created and try again.
```
Or similar.

**Comment by Malinskiy** [comment]
I'm in favor of printing a better exception here without a stacktrace. Probably should be implemented using an ExceptionHandler of sorts which for this particular type of exception will just print the message instead of printing the message + stacktrace
