### ISSUE TITLE
Marathon crash with ConcurrentModificationException

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#275]
```java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at com.malinskiy.marathon.android.executor.listeners.LogCatListener.testEnded(LogCatListener.kt:62)
	at com.malinskiy.marathon.android.executor.listeners.CompositeTestRunListener.testEnded(CompositeTestRunListener.kt:32)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:526)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:446)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:301)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:272)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:104)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:572)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:383)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:280)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:265)
	at com.malinskiy.marathon.android.executor.AndroidDeviceTestRunner.execute(AndroidDeviceTestRunner.kt:53)
	at com.malinskiy.marathon.android.AndroidDevice$execute$deferredResult$1.invokeSuspend(AndroidDevice.kt:148)
	at (Coroutine boundary.()
	at kotlinx.coroutines.DeferredCoroutine.await$suspendImpl(Builders.common.kt:99)
	at com.malinskiy.marathon.execution.device.DeviceActor$executeBatch$2.invokeSuspend(DeviceActor.kt:191)
Caused by: java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at com.malinskiy.marathon.android.executor.listeners.LogCatListener.testEnded(LogCatListener.kt:62)
	at com.malinskiy.marathon.android.executor.listeners.CompositeTestRunListener.testEnded(CompositeTestRunListener.kt:32)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:526)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:446)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:301)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:272)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:104)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:572)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:383)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:280)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:265)
	at com.malinskiy.marathon.android.executor.AndroidDeviceTestRunner.execute(AndroidDeviceTestRunner.kt:53)
	at com.malinskiy.marathon.android.AndroidDevice$execute$deferredResult$1.invokeSuspend(AndroidDevice.kt:148)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by Malinskiy** [comment]
fixed in #315
