### ISSUE TITLE
Marathon Gradle plugin does not look up apk location correctly

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#366]
I'm seeing:

```
Error while installing com.capitalone.android.identity.sample.debug, /Users/zaktaccardi/Development/git/mysdk/sample/build/outputs/apk/sourceMockInsecure/debug/sample-source-mock-insecure-debug.apk on EMULATOR30X0X5X0
com.malinskiy.marathon.android.exception.InstallException: com.android.ddmlib.InstallException: Local path doesn't exist.
        at com.malinskiy.marathon.android.ddmlib.DdmlibAndroidDevice.safeInstallPackage(DdmlibAndroidDevice.kt:212)
        at com.malinskiy.marathon.android.AndroidAppInstaller$reinstall$2.invokeSuspend(AndroidAppInstaller.kt:40)
        at com.malinskiy.marathon.android.AndroidAppInstaller$reinstall$2.invoke(AndroidAppInstaller.kt)
        at com.malinskiy.marathon.execution.RetryKt.withRetry(Retry.kt:10)
        at com.malinskiy.marathon.execution.RetryKt$withRetry$1.invokeSuspend(Retry.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:67)
        at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:319)
        at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:301)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:250)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:260)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:332)
        at kotlinx.coroutines.ResumeUndispatchedRunnable.run(Executors.kt:135)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.ddmlib.InstallException: Local path doesn't exist.
        at com.android.ddmlib.Device.installPackage(Device.java:1000)
        at com.malinskiy.marathon.android.ddmlib.DdmlibDeviceExtensionsKt.safeInstallPackage(DdmlibDeviceExtensions.kt:47)
        at com.malinskiy.marathon.android.ddmlib.DdmlibAndroidDevice.safeInstallPackage(DdmlibAndroidDevice.kt:210)
        ... 19 more
Caused by: com.android.ddmlib.SyncException: Local path doesn't exist.
        at com.android.ddmlib.SyncService.pushFile(SyncService.java:397)
        at com.android.ddmlib.Device.syncPackageToDevice(Device.java:1081)
        at com.android.ddmlib.Device.installPackage(Device.java:984)
        ... 21 more
```

This is likely because Marathon ~~hardcodes a gradle path~~ (looking to see why this is happening, as it works with agp `3.6.3` not `4.0.0-beta05`), rather that getting the apk as the output of the `:sample:packageSourceMockInsecureDebug` task.

note: `:sample` is an android application, and we use a custom naming convention for our apk
note: using marathon `0.5.2`

if I comment out the following in my `sample/build.gradle`

```groovy
android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "sample-v${sdkVersion}-${gitHash}-${variant.name}.apk"
    }
}
```

Then this works as expected with AGP `4.0.0-beta05`

**Comment by ZakTaccardi** [comment]
Actually, you're using:

https://github.com/Malinskiy/marathon/blob/cb0ac38638adabef7c15ec11d06d0a05ccc1d531/marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/extensions/BaseVariant.kt#L23

So I'm not sure how this issue is appearing for me

**Comment by ZakTaccardi** [comment]
this is an AGP bug - will file a google issue :)


EDIT: filed https://issuetracker.google.com/issues/155970562
