### ISSUE TITLE
Marathon is attempting to run analytics even when I have not explicitly enabled analytics

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#375]
I'm seeing:

```
Error not reported to Bugsnag - exception when making request
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2152)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
        at com.bugsnag.delivery.SyncHttpDelivery.deliver(SyncHttpDelivery.java:82)
        at com.bugsnag.delivery.AsyncHttpDelivery$3.run(AsyncHttpDelivery.java:94)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Even though I have not enabled analytics

**Comment by tagantroy** [comment]
Fixed in #385, you can disable bugsnap using `--bugsnap false`

**Comment by ZakTaccardi** [comment]
@tagantroy shouldn't bugsnag be disabled by default?

What is `bugsnap` as opposed to `bugsnag`?

What Gradle property can I specify for this, as I don't pass in CLI params?

**Comment by Malinskiy** [comment]
@ZakTaccardi bugsnag is something like [crashlytics](https://firebase.google.com/docs/crashlytics): it allows us to understand and prioritise issues based on the actual usage

**Comment by ZakTaccardi** [comment]
Yeah, I'm just confused by the `bugsnap` flag, as I think it should be `bugsnag`?

**Comment by Malinskiy** [comment]
@ZakTaccardi I think it's a typo :-)

**Comment by tagantroy** [comment]
Fix typo and added support for bugsnag switch to gradle plugin #394
