### ISSUE TITLE
Marathon is not terminated when exception occurs. 

### ISSUE THREAD

**Issue by sergiilisovskyi** [MarathonLabs/marathon#384]
Hi Anton,

**Steps to reproduce the behaviour**
1. Delete Marathonfile (or just provide invalid Marathonfile)
2. Start marathon  runner

**Actual behavior**
Job execution hangs with corresponding exception. Manual interaction is required to terminate batch job (ctrl + c)

**Expected behavior**
Marathon execution is totally terminated with corresponding message, like 
*Marathon run not started: ${Exception}*

**Logs and reports**
`19:08:41.468 [main] ERROR com.malinskiy.marathon.cli.config.ConfigFactory - No config D:\testProject\marathon\bin\Marathonfile present
19:08:41.482 [main] DEBUG com.bugsnag.Bugsnag - Reporting error to Bugsnag
Exception in thread "main" com.malinskiy.marathon.exceptions.ConfigurationException: No config D:\testProject\marathon\bin\Marathonfile present
        at com.malinskiy.marathon.cli.config.ConfigFactory.create(ConfigFactory.kt:27)
        at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt:41)
        at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt)
        at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
        at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
        at com.malinskiy.marathon.cli.ApplicationViewKt.main(ApplicationView.kt:28)`

**Actual for all platforms**

**Comment by tagantroy** [comment]
Hello @sergiilisovskyi, 
Thanks for this report. I fixed problem in #385

**Comment by sergiilisovskyi** [comment]
Thanks
