### ISSUE TITLE
Android plugin is not found

### ISSUE THREAD

**Issue by dmzhakov** [MarathonLabs/marathon#388]
Hi!

settings.gradle
```
pluginManagement {
    repositories {
        mavenCentral()
        jcenter()


    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'marathon') {
                useModule("com.malinskiy.marathon:marathon-gradle-plugin:${requested.version}")
            }
        }
    }
}


include ':app'
rootProject.buildFileName = "build.gradle"
rootProject.name = "My Application"

```

build.gradle

```
buildscript {
    ext.kotlin_version = "1.3.72"
    repositories {
        mavenCentral()
        google()
        jcenter()

    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"


    }
}

plugins {
    id 'marathon' version '0.5.2'
}


allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

error

```
* What went wrong:
A problem occurred configuring root project 'My Application'.
> Android plugin is not found
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'My Application'.
Caused by: java.lang.IllegalStateException: Android plugin is not found
 at com.malinskiy.marathon.MarathonPlugin$apply$2.execute(MarathonPlugin.kt:37)
 at com.malinskiy.marathon.MarathonPlugin$apply$2.execute(MarathonPlugin.kt:23)
```

What am I doing wrong?? :(

**Comment by PaladiRka** [comment]
@dmzhakov please, if you resolve your problem and closing issue, explain what helped you.

**Comment by Malinskiy** [comment]
@PaladiRka you need to apply the plugin on the gradle module with Android plugin. You're likely applying it to the root module at the moment

**Comment by PaladiRka** [comment]
Thank you.
