### ISSUE TITLE
java.lang.IllegalStateException: Already undeployed with ADAM 

### ISSUE THREAD

**Issue by plastiv** [MarathonLabs/marathon#516]
**Describe the bug**
Running marathon with gradle plugin integration and ADAM results in warning exception.  

**To Reproduce**
* Marathon 0.6.2
```
marathon {
    name = "storage tests"
    vendor = com.malinskiy.marathon.android.VendorType.ADAM
    autoGrantPermission = true
    debug = true
    testClassRegexes = [
            ".*Should*\$"
    ]
}
```
* `:storage:marathonDebugAndroidTest`

**Logs and reports**

```
java.lang.IllegalStateException: Already undeployed
        at io.vertx.core.impl.DeploymentManager$DeploymentImpl.doUndeploy(DeploymentManager.java:328)
        at io.vertx.core.impl.DeploymentManager$DeploymentImpl.undeploy(DeploymentManager.java:306)
        at io.vertx.core.impl.DeploymentManager.undeployVerticle(DeploymentManager.java:82)
        at io.vertx.core.impl.DeploymentManager.undeployAll(DeploymentManager.java:109)
        at io.vertx.core.impl.VertxImpl.lambda$close$14(VertxImpl.java:580)
        at io.vertx.core.impl.CloseHooks.run(CloseHooks.java:104)
        at io.vertx.core.impl.VertxImpl.close(VertxImpl.java:579)
        at io.vertx.core.impl.VertxImpl.close(VertxImpl.java:548)
        at com.malinskiy.adam.transport.vertx.VertxSocketFactory.close(VertxSocketFactory.kt:44)
        at com.malinskiy.marathon.android.adam.AdamDeviceProvider.terminate(AdamDeviceProvider.kt:158)
        at com.malinskiy.marathon.Marathon.onFinish(Marathon.kt:139)
        at com.malinskiy.marathon.Marathon.runAsync(Marathon.kt:120)
        at com.malinskiy.marathon.Marathon$runAsync$1.invokeSuspend(Marathon.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.malinskiy.marathon.Marathon.run(Marathon.kt:64)
        at com.malinskiy.marathon.MarathonRunTask.runMarathon(MarathonRunTask.kt:123)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:498)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:483)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:466)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:270)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:248)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:83)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:37)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:47)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:37)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:50)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:54)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:35)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:174)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:74)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:45)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:29)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:99)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:92)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:84)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:41)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:91)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:78)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:49)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:105)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:50)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:86)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:32)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:43)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:31)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$2.withWorkspace(ExecuteActionsTaskExecuter.java:283)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:49)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Devices (please complete the following information):**
 - Emulator sdk 29

**Comment by Malinskiy** [comment]
Was able to reproduce vert.x closing issue using CLI as well:

```
18:13:45.187 [main] INFO  c.m.marathon.cli.ApplicationView - Starting marathon v0.7.0
18:13:45.329 [main] INFO  c.m.m.e.BugsnagExceptionsReporter - Init BugSnag
18:13:45.371 [main] INFO  c.m.m.cli.config.ConfigFactory - Checking Marathonfile config
D 18:13:46.273 [main] <AdamDeviceProvider> Android Debug Bridge version 41
D 18:13:46.311 [DeviceMonitor] <AdamDeviceProvider> Device emulator-5554 changed state to CONNECTED
D 18:13:46.351 [AndroidDevice - execution - emulator-5554-1] <AndroidDevice> Device emulator-5554 booted!
I 18:13:46.450 [main] <com.malinskiy.marathon.Marathon> Scheduling 1 tests
D 18:13:46.451 [main] <com.malinskiy.marathon.Marathon> com.example.MainActivityTest#testText
I 18:13:46.452 [main] <com.malinskiy.marathon.Marathon> Output build/reports/marathon already exists
D 18:13:46.513 [main] <Scheduler> device emulator-5554 associated with poolId omni
D 18:13:46.513 [main] <Scheduler> pool actor omni is being created
D 18:13:46.527 [main] <DevicePoolActor[omni]> add device emulator-5554
D 18:13:46.532 [main] <DevicePool[omni]_DeviceActor[emulator-5554]> initialize emulator-5554
D 18:13:46.552 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Installing application output to emulator-5554
I 18:13:46.809 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Uninstalling com.example from emulator-5554
D 18:13:47.105 [AndroidDevice - execution - emulator-5554-1] <AndroidAppInstaller> Success
I 18:13:47.105 [AndroidDevice - execution - emulator-5554-1] <AndroidAppInstaller> Installing com.example, /home/pkunzip/Development/marathon/sample/android-app/app/build/outputs/apk/debug/app-debug.apk to emulator-5554
D 18:13:47.153 [AndroidDevice - execution - emulator-5554-1] <AndroidDevice> Transferred app-debug.apk to/from emulator-5554. 60045.45 KB/s (2642770 bytes in 0.0440)
D 18:13:47.201 [AndroidDevice - execution - emulator-5554-2] <AndroidDevice> /data/local/tmp/app-debug.apk synced in 28ms
D 18:13:47.944 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Success
D 18:13:47.944 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Installing instrumentation package to emulator-5554
I 18:13:48.135 [AndroidDevice - execution - emulator-5554-1] <AndroidAppInstaller> Uninstalling com.example.test from emulator-5554
D 18:13:48.394 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Success
I 18:13:48.395 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Installing com.example.test, /home/pkunzip/Development/marathon/sample/android-app/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk to emulator-5554
D 18:13:48.407 [AndroidDevice - execution - emulator-5554-1] <AndroidDevice> Transferred app-debug-androidTest.apk to/from emulator-5554. 89000.00 KB/s (979211 bytes in 0.0110)
D 18:13:48.433 [AndroidDevice - execution - emulator-5554-1] <AndroidDevice> /data/local/tmp/app-debug-androidTest.apk synced in 23ms
D 18:13:48.923 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Success
D 18:13:48.923 [AndroidDevice - execution - emulator-5554-2] <AndroidAppInstaller> Prepare installation finished for emulator-5554
D 18:13:48.959 [main] <QueueActor[DevicePoolId(name=omni)]> request next batch for device emulator-5554
D 18:13:48.960 [main] <QueueActor[DevicePoolId(name=omni)]> sending next batch for device emulator-5554
D 18:13:48.962 [main] <DevicePool[omni]_DeviceActor[emulator-5554]> executeBatch emulator-5554
D 18:13:48.971 [AndroidDevice - execution - emulator-5554-1] <AndroidDeviceTestRunner> tests = [com.example.MainActivityTest#testText]
D 18:13:49.138 [AndroidDevice - execution - emulator-5554-2] <AndroidDeviceTestRunner> Package com.example cleared: Success
D 18:13:49.301 [AndroidDevice - execution - emulator-5554-1] <AndroidDeviceTestRunner> Package com.example.test cleared: Success
D 18:13:49.363 [AndroidDevice - execution - emulator-5554-2] <AndroidDeviceTestRunner> Execution started
I 18:13:50.354 [AndroidDevice - execution - emulator-5554-1] <DebugTestRunListener> testRunStarted emulator-5554
I 18:13:50.355 [AndroidDevice - execution - emulator-5554-1] <DebugTestRunListener> testStarted emulator-5554 test = TestIdentifier(className=com.example.MainActivityTest, testName=testText)
00% | [omni]-[emulator-5554] com.example.MainActivityTest#testText started
D 18:13:51.661 [AndroidDevice - execution - emulator-5554-1] <AndroidDevice> screenrecord output:
 ShellCommandResult(output=, exitCode=0)
D 18:13:51.661 [AndroidDevice - execution - emulator-5554-1] <ScreenRecorder> Recording finished in 1306ms /sdcard/com.example.MainActivityTest-testText-d8a9368c-ab2f-41b1-b11c-b98244ebd36f.mp4
I 18:13:52.370 [AndroidDevice - execution - emulator-5554-1] <DebugTestRunListener> testEnded emulator-5554 test = TestIdentifier(className=com.example.MainActivityTest, testName=testText)
100% | [omni]-[emulator-5554] com.example.MainActivityTest#testText ended
I 18:13:52.374 [AndroidDevice - execution - emulator-5554-1] <DebugTestRunListener> testRunEnded elapsedTime 1965
D 18:13:52.374 [AndroidDevice - execution - emulator-5554-1] <FileSyncTestRunListener> Pulling into /home/pkunzip/Development/marathon/sample/android-app/build/reports/marathon/device-files/allure-results
D 18:13:52.404 [AndroidDevice - execution - emulator-5554-2] <AndroidDevice> Transferred 510a194d-d446-4f5a-9098-02663bd31f84-result.json to/from emulator-5554. 83.33 KB/s (1714 bytes in 0.0120)
D 18:13:52.404 [AndroidDevice - execution - emulator-5554-2] <FileSyncTestRunListener> Pulling into /home/pkunzip/Development/marathon/sample/android-app/build/reports/marathon/device-files/omni/coverage
D 18:13:52.417 [AndroidDevice - execution - emulator-5554-1] <AndroidDevice> Transferred coverage-d8a9368c-ab2f-41b1-b11c-b98244ebd36f.ec to/from emulator-5554. 0.00 KB/s (139 bytes in 0.0050)
D 18:13:52.417 [AndroidDevice - execution - emulator-5554-1] <AndroidDeviceTestRunner> Execution finished
D 18:13:52.418 [main] <QueueActor[DevicePoolId(name=omni)]> handle test results emulator-5554
D 18:13:52.419 [main] <QueueActor[DevicePoolId(name=omni)]> request next batch for device emulator-5554
E 18:13:52.426 [vert.x-eventloop-thread-13] <io.vertx.core.impl.DeploymentManager> Undeploy failed
java.lang.IllegalStateException: Unknown deployment
	at io.vertx.core.impl.DeploymentManager.undeployVerticle(DeploymentManager.java:80)
	at io.vertx.core.impl.DeploymentManager.undeployAll(DeploymentManager.java:109)
	at io.vertx.core.impl.VertxImpl.lambda$close$14(VertxImpl.java:580)
	at io.vertx.core.impl.CloseHooks.run(CloseHooks.java:104)
	at io.vertx.core.impl.VertxImpl.close(VertxImpl.java:579)
	at io.vertx.core.impl.VertxImpl.close(VertxImpl.java:548)
	at com.malinskiy.adam.transport.vertx.VertxSocketFactory.close(VertxSocketFactory.kt:44)
	at com.malinskiy.marathon.android.adam.AdamDeviceProvider.terminate(AdamDeviceProvider.kt:158)
	at com.malinskiy.marathon.Marathon.onFinish(Marathon.kt:139)
	at com.malinskiy.marathon.Marathon.runAsync(Marathon.kt:120)
	at com.malinskiy.marathon.Marathon$runAsync$1.invokeSuspend(Marathon.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.malinskiy.marathon.Marathon.run(Marathon.kt:64)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt:51)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at com.malinskiy.marathon.cli.ApplicationViewKt.main(ApplicationView.kt:29)
Allure environment data saved.
Marathon run finished:
Device pool omni:
	1 passed, 0 failed, 0 ignored tests
	Flakiness overhead: 0ms
	Raw: 1 passed, 0 failed, 0 ignored, 0 incomplete tests
Total time: 0H 0m 6s

I 18:13:52.603 [main] <c.m.m.e.BugsnagExceptionsReporter> Finish BugSnag
D 18:13:52.603 [main] <com.bugsnag.Bugsnag> Closing connection to Bugsnag
marathon v0.7.0: Test run finished
D 18:13:52.605 [Thread-2] <com.bugsnag.Bugsnag> Closing connection to Bugsnag
```

**Comment by Malinskiy** [comment]
This shouldn't be a problem anymore on the recent versions @plastiv to my knowledge
Please close the issue unless there is anything else

**Comment by plastiv** [comment]
Thank you 🎉
