### ISSUE TITLE
Filename creation error: IllegalArgumentException: Requested character count -1 is less than zero.

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#619]
**Describe the bug**
I'm seeing the following exception in CI when running `7.0` of Marathon. Not sure why CI is different than local.

**Devices (please complete the following information):**
 - Device: emulator API 30
 - OS: MacOS

**Additional context**
It also retries indefinitely for some reason.

```
[main @coroutine#59] <D.0.0.1:5037:emulator-5578]> Unknown vendor exception caught. Considering this a recoverable error
```

Stacktrace:

```
java.lang.IllegalArgumentException: Requested character count -1 is less than zero.
	at kotlin.text.StringsKt___StringsKt.take(_Strings.kt:565)
	at com.malinskiy.marathon.io.FileManager.createFilename(FileManager.kt:84)
	at com.malinskiy.marathon.io.FileManager.createFile(FileManager.kt:20)
 	at com.malinskiy.marathon.report.logs.LogWriter.saveLogs(LogWriter.kt:12)
 	at com.malinskiy.marathon.android.executor.listeners.LogCatListener.testEnded(LogCatListener.kt:42)
 	at com.malinskiy.marathon.android.executor.listeners.CompositeTestRunListener.testEnded(CompositeTestRunListener.kt:35)
 	at com.malinskiy.marathon.android.executor.listeners.CompositeTestRunListener$testEnded$1.invokeSuspend(CompositeTestRunListener.kt)
 	at (Coroutine boundary.()
 	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:101)
 	at com.malinskiy.marathon.android.adam.AndroidDeviceTestRunner.execute(AndroidDeviceTestRunner.kt:64)
 	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2$1.invokeSuspend(AdamAndroidDevice.kt:358)
 	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2.invokeSuspend(AdamAndroidDevice.kt:356)
 	at com.malinskiy.marathon.android.adam.AdamAndroidDevice.execute(AdamAndroidDevice.kt:360)
 	at com.malinskiy.marathon.execution.device.DeviceActor$executeBatch$2.invokeSuspend(DeviceActor.kt:187)
 Caused by: java.lang.IllegalArgumentException: Requested character count -1 is less than zero.
 	at kotlin.text.StringsKt___StringsKt.take(_Strings.kt:565)
 	at com.malinskiy.marathon.io.FileManager.createFilename(FileManager.kt:84)
 	at com.malinskiy.marathon.io.FileManager.createFile(FileManager.kt:20)
 	at com.malinskiy.marathon.report.logs.LogWriter.saveLogs(LogWriter.kt:12)
 	at com.malinskiy.marathon.android.executor.listeners.LogCatListener.testEnded(LogCatListener.kt:42)
 	at com.malinskiy.marathon.android.executor.listeners.CompositeTestRunListener.testEnded(CompositeTestRunListener.kt:35)
 	at com.malinskiy.marathon.android.executor.listeners.CompositeTestRunListener$testEnded$1.invokeSuspend(CompositeTestRunListener.kt)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:834

```

**Comment by ZakTaccardi** [comment]
I was able to replicate this issue with the following test code:

```kotlin
  @Test
  fun testTakeIllegalStateException() {
    val test = com.malinskiy.marathon.test.Test(
        pkg = "com.xxyyzzxxyy.android.abcdefgh.abcdefghi",
        clazz = "PackageNameTest",
        method = "useAppContext",
        metaProperties = emptyList()
    )
    val fileType = FileType.LOG

    val limit = 40

    val testBatchId = "b1ef4450-db22-403b-977c-56fdca64c800"

    val testSuffix = "${testBatchId.let { "-$it" }}.${fileType.suffix}"
    val rawTestName = test.toTestName().escape()

    // `.take(..)` crashes here bc `limit - testSuffix.length == -1`
    val testName = rawTestName.take(limit - testSuffix.length)
    val fileName = "$testName$testSuffix"

    if (rawTestName.length > testName.length) {
        println("File name length cannot exceed $limit characters and has been trimmed to $fileName and can create a conflict. This happened because the combination of file path, test class name, and test name is too long.")
    }
    println(fileName)
}
```

**Comment by ZakTaccardi** [comment]
side note, but why is `MAX_PATH` `255` characters? ([source](https://github.com/MarathonLabs/marathon/blob/3658eecfcf1133e2f2a3a2b98035b0eb5924bc25/core/src/main/kotlin/com/malinskiy/marathon/io/FileManager.kt#L95)). My understanding is that this limitation only applies to files or directory names themselves, and not the full path

**Comment by ZakTaccardi** [comment]
I modified the source, bumped the `MAX_PATH` to 1000, and I haven't seen any issues with this

**Comment by Malinskiy** [comment]
The issue here is that you're writing to a path that is so long that there is no space left to actually name the log file. I'm not sure what I can do here besides just making a better exception message.

Side note: The minimum limit for the MAX_PATH is defined [here](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)

**Comment by ZakTaccardi** [comment]
@Malinskiy this only affects Windows (and applications can opt in to the longer length on Windows 10). We're linux/mac only, so we are unaffected by this limitation.

It would be great to provide a way to inject the limit via the marathon gradle extension. Maybe something like:

```kts
marathon {
  ignoreWindowsMaxPathLimit = true
}
```

Otherwise, for us to consume a new marathon release, we have to fork it internally and modify the source of `MAX_PATH` to bump the limit.

Thanks!

**Comment by ZakTaccardi** [comment]
another solution would be to create dynamic limits based on mac vs windows vs linux

**Comment by Malinskiy** [comment]
While this particular example is Window's NTFS limitation, I can't guarantee that there is no Linux filesystem that doesn't have the same limitation. Currently, there is no API for JVM to capture the max filepath + max filename, so until such an API exists it is not a good idea to have `switch(os.version)` in the code: the real limitation is on the filesystem implementation and there is no API to get the filesystem implementation as well.

I've created a PR with a better error message for the issue at hand.

If you want to file another one with the filesystem limitations problem - feel free to do that.
