### ISSUE TITLE
Unable to finish running tests

### ISSUE THREAD

**Issue by MashhoudFarahrooz** [MarathonLabs/marathon#786]
**Describe the bug**
After finishing running tests, never complete the marathon step until killed by GitHub action rules.

marathon version `0.8.1`

**Expected behavior**
Finish running tests.

**Logs and reports**
```
Exception in thread "DeviceMonitor @coroutine#7" com.malinskiy.adam.exception.RequestRejectedException: Unexpected string length: 
	at com.malinskiy.adam.extension.SocketKt.readProtocolString(Socket.kt:106)
	at com.malinskiy.adam.extension.SocketKt$readProtocolString$1.invokeSuspend(Socket.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:[304](https://github.com/albumprinter/editor_mobile/actions/runs/4721723234/jobs/8375463038#step:5:304))
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineId(7), "coroutine#7":StandaloneCoroutine{Cancelling}@218d1727, java.util.concurrent.ScheduledThreadPoolExecutor@7d9b92f9[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 18]]
```

**Devices (please complete the following information):**
 - Device: emulator
 - OS: Android 13 (33)

**Additional context**
This tests runs on a mac mini with intel chip

**Comment by Malinskiy** [comment]
Hey @MashhoudFarahrooz, thanks for submitting the issue

From the short snippet of log you provided it seems like the TCP connection with adb server is improperly closed. There are multiple reasons for it: crashed adb server, network router socket termination or just an Android device crash to name a few. Are you sure that tests actually finished (since you didn't provide the full log)? Is this problem reproducible on CI only or is it reproducible on your local machine as well?

**Comment by MashhoudFarahrooz** [comment]
Hey @Malinskiy, I changed my build machine to a Mac mini with an m1 chip, and I no longer have this error.
