### ISSUE TITLE
ConcurrentModificationException in LogcatManager

### ISSUE THREAD

**Issue by VictorIreri** [MarathonLabs/marathon#882]
**Describe the bug**
I saw exception in the logs today for the first time when running tests on physical android devices. The test execution was able to continue after a small delay so it may have happened before and I didn't notice. I don't have much information about how to reproduce this unfortunately but hopefully the details below will be useful.

**Expected behaviour**
Exception shouldn't occur.

**Logs and reports**
```
Exception in thread "LogcatManager-3 @coroutine#119" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice.onLine(AdamAndroidDevice.kt:527)
	at com.malinskiy.marathon.android.adam.LogcatManager$subscribe$1$1.invokeSuspend(LogcatManager.kt:38)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46)
	at com.malinskiy.marathon.android.adam.LogcatManager$subscribe$1.invokeSuspend(LogcatManager.kt:27)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(119), "coroutine#119":StandaloneCoroutine{Cancelling}@3dd9dee0, java.util.concurrent.ScheduledThreadPoolExecutor@49c409da[Running, pool size = 4, active threads = 1, queued tasks = 0, completed tasks = 308665]]
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice.onLine(AdamAndroidDevice.kt:527)
	at com.malinskiy.marathon.android.adam.LogcatManager$subscribe$1$1.invokeSuspend(LogcatManager.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Devices (please complete the following information):**
 - Marathon version: 0.9.0
 - Running on Macbook Pro 16" - MacOS Sonoma 14.2.1
 - Android Test devices: Pixel 3a - Android 12 (x1), Moto E6s - Android 9 (x5)

**Comment by Malinskiy** [comment]
Hey @VictorIreri 
Currently, the access to log listeners is synchronized for add and remove, but not for traversal.
I see two options: either synchronize the traversal or use some implementation of List that is thread-safe for our low-modification and high-traversal case.
WDYT?

**Comment by VictorIreri** [comment]
Sorry I missed your response. Thanks for the fix.

**Comment by Malinskiy** [comment]
All good mate. Cheers
